import { createHash } from "crypto"
import type { DifferentialEntry } from "@/types"

export const DIFFERENTIALS_VERSION = "differentials-v1"

// Keyed by ailment slug. Populated for all 19 ailments. The nine
// dermatological/morphological slugs (acne, candidal-stomatitis, conjunctivitis,
// dermatitis, herpes-labialis, impetigo, insect-bites-urticaria, tick-bites-lyme,
// hemorrhoids) also carry dermnetLinks. Every url is a literal constant (no
// interpolation) so no patient context can ever leak into an outbound request.
export const DIFFERENTIALS: Record<string, DifferentialEntry> = {
  "acne": {
    differentials: [
      { name: "Folliculitis",
        distinguishingFeatures: "Discrete follicular pustules; less comedonal than acne; may be staph",
        disposition: "treat_in_tool" },
      { name: "Rosacea",
        distinguishingFeatures: "Adult onset, central face flush, telangiectasia, no comedones",
        disposition: "refer" },
      { name: "Perioral dermatitis",
        distinguishingFeatures: "Papules/pustules around mouth/nose, sparing lip border; often topical-steroid linked",
        disposition: "treat_in_tool" },
    ],
    dermnetLinks: [
      { label: "Acne vulgaris — DermNet NZ", url: "https://dermnetnz.org/topics/acne-vulgaris", topic: "acne-vulgaris" },
      { label: "Rosacea — DermNet NZ", url: "https://dermnetnz.org/topics/rosacea", topic: "rosacea" },
    ],
  },
  "allergic-rhinitis": {
    differentials: [
      { name: "Viral upper respiratory infection",
        distinguishingFeatures: "Acute onset <10 days, fever/malaise, mucopurulent later; not recurrent seasonal",
        disposition: "otc_only" },
      { name: "Vasomotor (non-allergic) rhinitis",
        distinguishingFeatures: "No itch/eye symptoms, triggered by temperature/odours, negative allergy testing",
        disposition: "otc_only" },
      { name: "Acute bacterial sinusitis",
        distinguishingFeatures: "Facial pain/pressure, purulent discharge >10 days or worsening after initial improvement",
        disposition: "refer" },
      { name: "Rhinitis medicamentosa",
        distinguishingFeatures: "Rebound congestion from prolonged topical decongestant use (>3-5 days)",
        disposition: "otc_only" },
    ],
    dermnetLinks: [],
  },
  "aphthous-ulcers": {
    differentials: [
      { name: "Intraoral herpes simplex",
        distinguishingFeatures: "Vesicles coalesce on keratinized mucosa (hard palate/gingiva); aphthae favour non-keratinized mucosa",
        disposition: "treat_in_tool" },
      { name: "Oral candidiasis (thrush)",
        distinguishingFeatures: "Wipeable white plaques with erythematous base, not discrete round ulcers",
        disposition: "treat_in_tool" },
      { name: "Hand-foot-and-mouth disease",
        distinguishingFeatures: "Multi-site lesions with palmar/plantar involvement, systemic symptoms, child contact",
        disposition: "refer" },
      { name: "Traumatic ulcer",
        distinguishingFeatures: "Single ulcer matching a sharp tooth/appliance; heals once irritant removed",
        disposition: "otc_only" },
    ],
    dermnetLinks: [],
  },
  "candidal-stomatitis": {
    differentials: [
      { name: "Oral lichen planus",
        distinguishingFeatures: "Lace-like white striae (Wickham), erosive variants; bilateral; not wipeable",
        disposition: "refer" },
      { name: "Leukoplakia",
        distinguishingFeatures: "Non-wipeable fixed white plaque, often lateral tongue; cannot scrape off; needs biopsy",
        disposition: "refer" },
      { name: "Aphthous ulceration",
        distinguishingFeatures: "Discrete painful round ulcers on non-keratinized mucosa, no diffuse plaque",
        disposition: "treat_in_tool" },
      { name: "Hairy leukoplakia (immunocompromise)",
        distinguishingFeatures: "Corrugated white lateral tongue that does not wipe off; consider HIV workup",
        disposition: "refer" },
    ],
    dermnetLinks: [
      { label: "Oral candidiasis — DermNet NZ", url: "https://dermnetnz.org/topics/oral-candidiasis", topic: "oral-candidiasis" },
      { label: "Aphthous stomatitis — DermNet NZ", url: "https://dermnetnz.org/topics/aphthous-ulcers", topic: "aphthous-ulcers" },
    ],
  },
  "conjunctivitis": {
    differentials: [
      { name: "Viral conjunctivitis",
        distinguishingFeatures: "Watery, preauricular lymphadenopathy, highly contagious; typically self-limited",
        disposition: "otc_only" },
      { name: "Allergic conjunctivitis",
        distinguishingFeatures: "Bilateral itching, watery, atopic history; stringy mucus",
        disposition: "treat_in_tool" },
      { name: "Acute angle-closure glaucoma",
        distinguishingFeatures: "Severe pain, haloes, fixed mid-dilated pupil, raised IOP; ophthalmic emergency",
        disposition: "refer" },
      { name: "Keratitis / uveitis / corneal abrasion",
        distinguishingFeatures: "Deep eye pain, photophobia, reduced vision; not a simple surface redness",
        disposition: "refer" },
    ],
    dermnetLinks: [
      { label: "Conjunctivitis — DermNet NZ", url: "https://dermnetnz.org/topics/conjunctivitis", topic: "conjunctivitis" },
    ],
  },
  "dermatitis": {
    differentials: [
      { name: "Irritant diaper dermatitis",
        distinguishingFeatures: "Folds SPARED; confluent erythema over convex surfaces",
        disposition: "treat_in_tool" },
      { name: "Candidal diaper dermatitis",
        distinguishingFeatures: "Folds INVOLVED + satellite pustules; bright-red, beefy erythema",
        disposition: "treat_in_tool" },
      { name: "Seborrhoeic dermatitis",
        distinguishingFeatures: "Greasy scale on scalp/face/folds; less pruritic than atopic",
        disposition: "treat_in_tool" },
      { name: "Allergic contact dermatitis",
        distinguishingFeatures: "Pattern matches contactant (e.g. wipe, dye); sharply demarcated, pruritic",
        disposition: "treat_in_tool" },
      { name: "Psoriasis (napkin or plaque)",
        distinguishingFeatures: "Well-demarcated, silvery scale; +/- family history; often elbows/knees",
        disposition: "refer" },
    ],
    clinicalPearls: ["Steroid for irritant/atopic; azole/nystatin ONLY if candidal features present."],
    dermnetLinks: [
      { label: "Irritant contact dermatitis — DermNet NZ", url: "https://dermnetnz.org/topics/irritant-contact-dermatitis", topic: "irritant-cd" },
      { label: "Candidal napkin dermatitis — DermNet NZ", url: "https://dermnetnz.org/topics/candidal-napkin-dermatitis", topic: "candidal-napkin" },
    ],
  },
  "dysmenorrhea": {
    differentials: [
      { name: "Secondary dysmenorrhea / endometriosis",
        distinguishingFeatures: "Later onset, progressively worsening pain, dyspareunia, chronic pelvic pain; not responsive to first-line",
        disposition: "refer" },
      { name: "Pelvic inflammatory disease",
        distinguishingFeatures: "Bilateral lower abdominal pain, cervical motion tenderness, fever, discharge",
        disposition: "refer" },
      { name: "Uterine fibroids",
        distinguishingFeatures: "Heavy/prolonged bleeding, bulk symptoms, anaemia",
        disposition: "refer" },
      { name: "Ectopic pregnancy",
        distinguishingFeatures: "Amenorrhoea with unilateral pain and spotting; reproductive-age patient; emergency",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "gerd": {
    differentials: [
      { name: "Cardiac chest pain (angina/ACS)",
        distinguishingFeatures: "Exertional, pressure/radiation to arm/jaw, diaphoresis; not related to meals",
        disposition: "refer" },
      { name: "Peptic ulcer disease",
        distinguishingFeatures: "Epigastric burning, relieved or worsened by food, possible melena/anaemia",
        disposition: "treat_in_tool" },
      { name: "Biliary disease (cholecystitis/biliary colic)",
        distinguishingFeatures: "Right upper quadrant pain, post-fatty-meal, possible fever; not burning retrosternal",
        disposition: "refer" },
      { name: "Esophageal or gastric malignancy",
        distinguishingFeatures: "Dysphagia, weight loss, early satiety, older patient with alarm features",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "hemorrhoids": {
    differentials: [
      { name: "Anal fissure",
        distinguishingFeatures: "Sharp tearing pain with defecation, bright red blood on tissue, posterior midline",
        disposition: "treat_in_tool" },
      { name: "Perianal abscess / fistula",
        distinguishingFeatures: "Throbbing pain, fluctuance, fever, purulent drainage",
        disposition: "refer" },
      { name: "Perianal Crohn disease",
        distinguishingFeatures: "Recurrent fissures, skin tags, fistulae, underlying IBD; complex/indurated lesions",
        disposition: "refer" },
      { name: "Colorectal malignancy",
        distinguishingFeatures: "Change in bowel habit, weight loss, dark blood mixed in stool, older patient",
        disposition: "refer" },
    ],
    dermnetLinks: [
      { label: "Haemorrhoids — DermNet NZ", url: "https://dermnetnz.org/topics/haemorrhoids", topic: "haemorrhoids" },
      { label: "Anal fissure — DermNet NZ", url: "https://dermnetnz.org/topics/anal-fissure", topic: "anal-fissure" },
    ],
  },
  "herpes-labialis": {
    differentials: [
      { name: "Aphthous ulcer",
        distinguishingFeatures: "Inside the mouth on movable mucosa, no preceding vesicle, not contagious",
        disposition: "treat_in_tool" },
      { name: "Impetigo",
        distinguishingFeatures: "Honey-coloured crust, not vesicular, may spread around nose/mouth",
        disposition: "treat_in_tool" },
      { name: "Angular cheilitis",
        distinguishingFeatures: "Bilateral mouth-corner fissuring, often candidal/nutritional; not a grouped vesicle",
        disposition: "treat_in_tool" },
      { name: "Hand-foot-and-mouth disease",
        distinguishingFeatures: "Multi-site vesicles with palm/sole involvement, systemic, child contact",
        disposition: "refer" },
    ],
    dermnetLinks: [
      { label: "Herpes simplex — DermNet NZ", url: "https://dermnetnz.org/topics/herpes-simplex-virus", topic: "hsv" },
      { label: "Aphthous ulcers — DermNet NZ", url: "https://dermnetnz.org/topics/aphthous-ulcers", topic: "aphthous-ulcers" },
    ],
  },
  "impetigo": {
    differentials: [
      { name: "Herpes simplex (cold sore/fever blister)",
        distinguishingFeatures: "Grouped vesicles on erythematous base, prodromal tingling; not honey-crusted",
        disposition: "treat_in_tool" },
      { name: "Atopic dermatitis, impetiginized (secondarily infected)",
        distinguishingFeatures: "Underlying eczema history, dry/pruritic patches, less sharply demarcated",
        disposition: "treat_in_tool" },
      { name: "Contact dermatitis",
        distinguishingFeatures: "Geometric/linear pattern matching the contactant; pruritic, weeping",
        disposition: "treat_in_tool" },
      { name: "Cellulitis / erysipelas",
        distinguishingFeatures: "Spreading erythema with systemic fever, warmth, tenderness; unwell patient",
        disposition: "refer" },
    ],
    dermnetLinks: [
      { label: "Impetigo — DermNet NZ", url: "https://dermnetnz.org/topics/impetigo", topic: "impetigo" },
      { label: "Herpes simplex — DermNet NZ", url: "https://dermnetnz.org/topics/herpes-simplex-virus", topic: "hsv" },
    ],
  },
  "insect-bites-urticaria": {
    differentials: [
      { name: "Cellulitis",
        distinguishingFeatures: "Spreading warmth/erythema with systemic fever; not itchy urticated wheals",
        disposition: "refer" },
      { name: "Erythema multiforme",
        distinguishingFeatures: "Target lesions, often palms/soles/mucosa; HSV or drug trigger",
        disposition: "refer" },
      { name: "Drug eruption",
        distinguishingFeatures: "Generalized symmetric maculopapular rash days after a new medication",
        disposition: "otc_only" },
      { name: "Scabies",
        distinguishingFeatures: "Nocturnal pruritus, burrows in finger webs/waist/genitals, household spread",
        disposition: "treat_in_tool" },
    ],
    dermnetLinks: [
      { label: "Urticaria — DermNet NZ", url: "https://dermnetnz.org/topics/urticaria", topic: "urticaria" },
      { label: "Insect bites — DermNet NZ", url: "https://dermnetnz.org/topics/insect-bites", topic: "insect-bites" },
    ],
  },
  "musculoskeletal": {
    differentials: [
      { name: "Fracture",
        distinguishingFeatures: "Focal bony tenderness, deformity, inability to bear load; high-energy mechanism",
        disposition: "refer" },
      { name: "Tendon or ligament rupture",
        distinguishingFeatures: "Sudden pop, loss of active function, palpable gap; e.g. Achilles",
        disposition: "refer" },
      { name: "Septic arthritis",
        distinguishingFeatures: "Hot swollen joint, severe pain at rest, fever; cannot exclude on exam alone",
        disposition: "refer" },
      { name: "Deep vein thrombosis",
        distinguishingFeatures: "Calf swelling/warmth, risk factors, unilateral; consider if lower limb",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "nausea-vomiting": {
    differentials: [
      { name: "Nausea and vomiting of pregnancy",
        distinguishingFeatures: "Reproductive-age patient, morning predominance, positive pregnancy test",
        disposition: "treat_in_tool" },
      { name: "Medication-induced",
        distinguishingFeatures: "Onset temporally related to a new drug (e.g. NSAID, opioid, antibiotic)",
        disposition: "otc_only" },
      { name: "Bowel obstruction",
        distinguishingFeatures: "Colicky pain, distension, constipation/obstipation, prior surgery",
        disposition: "refer" },
      { name: "Appendicitis / acute abdomen",
        distinguishingFeatures: "Migrating RLQ pain, rebound, fever, anorexia",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "nvp": {
    differentials: [
      { name: "Hyperemesis gravidarum",
        distinguishingFeatures: "Intractable vomiting with weight loss >5%, dehydration, ketonuria, electrolyte derangement",
        disposition: "refer" },
      { name: "Gestational trophoblastic disease (molar pregnancy)",
        distinguishingFeatures: "Excessive vomiting, vaginal bleeding, uterus large for dates, high hCG",
        disposition: "refer" },
      { name: "Acute gastroenteritis",
        distinguishingFeatures: "Acute self-limited, diarrhoea prominent, contacts; not morning-predominant",
        disposition: "otc_only" },
      { name: "Urinary tract infection in pregnancy",
        distinguishingFeatures: "Dysuria/frequency, flank pain; nausea can accompany; needs culture",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "pinworms": {
    differentials: [
      { name: "Anal fissure / haemorrhoids (anal pruritus)",
        distinguishingFeatures: "Bleeding with defecation, palpable tag/lump; pruritus secondary to irritation",
        disposition: "treat_in_tool" },
      { name: "Perianal candidiasis / dermatitis",
        distinguishingFeatures: "Moist intertriginous erythema, satellite lesions; no nocturnal worm migration",
        disposition: "treat_in_tool" },
      { name: "Household reinfestation",
        distinguishingFeatures: "Symptoms recur within weeks; treat all household contacts simultaneously",
        disposition: "otc_only" },
      { name: "Sexually transmitted proctitis",
        distinguishingFeatures: "Discharge, tenesmus, risk factors; consider testing",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "tick-bites-lyme": {
    differentials: [
      { name: "Cellulitis",
        distinguishingFeatures: "Spreading warmth/erythema with fever; not a slowly expanding central-clearing ring",
        disposition: "refer" },
      { name: "Necrotic spider bite",
        distinguishingFeatures: "Rapid necrotic eschar, severe pain, systemic features; not expanding",
        disposition: "refer" },
      { name: "Fixed drug eruption",
        distinguishingFeatures: "Reappears same site with a medication, round pigmented plaque; not expanding",
        disposition: "otc_only" },
      { name: "Southern tick-associated rash illness (STARI)",
        distinguishingFeatures: "Lone-star tick bite, expanding rash after a lone-star tick; less systemic",
        disposition: "refer" },
    ],
    dermnetLinks: [
      { label: "Lyme disease — DermNet NZ", url: "https://dermnetnz.org/topics/lyme-disease", topic: "lyme-disease" },
      { label: "Tick bites — DermNet NZ", url: "https://dermnetnz.org/topics/tick-bites", topic: "tick-bites" },
    ],
  },
  "uti": {
    differentials: [
      { name: "Vaginitis (candidiasis / bacterial vaginosis)",
        distinguishingFeatures: "Vaginal discharge/itch, dyspareunia; no frequency/urgency/suprapubic pain",
        disposition: "treat_in_tool" },
      { name: "Sexually transmitted infection / urethritis",
        distinguishingFeatures: "Recent partner, urethral/vaginal discharge, risk history; needs testing",
        disposition: "refer" },
      { name: "Interstitial cystitis / bladder pain syndrome",
        distinguishingFeatures: "Chronic pelvic pain with filling, negative cultures, no infection",
        disposition: "refer" },
      { name: "Pyelonephritis",
        distinguishingFeatures: "Flank pain, fever/chills, nausea/vomiting; upper-tract involvement",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
  "vvc": {
    differentials: [
      { name: "Bacterial vaginosis",
        distinguishingFeatures: "Thin malodorous (fishy) homogeneous discharge, pH >4.5; minimal itching",
        disposition: "otc_only" },
      { name: "Trichomoniasis (STI)",
        distinguishingFeatures: "Frothy yellow-green discharge, strawberry cervix, risk history; needs testing",
        disposition: "refer" },
      { name: "Contact vulvovaginitis (irritant/allergic)",
        distinguishingFeatures: "Exposure to hygiene product/fragrance, no cottage-cheese discharge",
        disposition: "otc_only" },
      { name: "Atrophic vaginitis",
        distinguishingFeatures: "Post-menopausal, dryness/dyspareunia, pale thin mucosa; not infectious",
        disposition: "refer" },
    ],
    dermnetLinks: [],
  },
}

export function computeDifferentialsHash(
  entries: Record<string, DifferentialEntry> = DIFFERENTIALS,
): string {
  const tuples = Object.keys(entries)
    .sort()
    .flatMap((slug) =>
      entries[slug].differentials.map((d) => `${slug}|${d.name}|${d.disposition}`),
    )
    .join("\n")
  return createHash("sha256").update(tuples).digest("hex")
}

export const DIFFERENTIALS_HASH = computeDifferentialsHash(DIFFERENTIALS)
